# Generated by Django 4.2.7 on 2024-04-09 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_address_customer_delete_main_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
    ]
