# Generated by Django 4.2.7 on 2024-04-09 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.address'),
        ),
    ]
