# Generated by Django 4.2.7 on 2024-04-09 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_order_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usermodel',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
