# Generated by Django 4.2.7 on 2024-04-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product_seller_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(help_text='must enter house-number street,city,zip-code and state,country'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('done', 'done'), ('pending', 'pending')], default='pending', max_length=50),
        ),
    ]
