# Generated by Django 4.2.7 on 2024-04-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_order_total_amount_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('done', 'done')], default='pending', max_length=50),
        ),
    ]
