# Generated by Django 4.2.7 on 2024-04-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('done', 'done'), ('pending', 'pending')], default='pending', max_length=50),
        ),
    ]
