# Generated by Django 4.2.7 on 2024-04-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_customer_address_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='password2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
